// Simple Object Creation
// const circle = {

// radius: 1,

//     location: {

//     x: 0,

//     y: 0

//     },

//     isVisible: true,

//     draw: function() {

//     console.log('Draw');

//     }

//     };
//     circle.draw(); // Output: Draw

// Factory Functions
// function createCircle(radius) {
//   return {
//     radius,

//     draw() {
//       console.log("Draw");
//     },
//   };
// }

// const circle1 = createCircle(1);

// const circle2 = createCircle(2);

// circle1.draw(); // Output: Draw

// Pascal Notation
// function Circle(radius) {
//   this.radius = radius;

//   this.draw = function () {
//     console.log("Draw");
//   };
// }

// const circle = new Circle(1);

// circle.draw(); // Output: Draw

// let randomValue = Math.random(); // Generates a random number between 0 and 1

// let roundedValue = Math.round(1.95); // Rounds 1.95 to

// const now = new Date(); // Current date and time

// const specificDate = new Date('May 11 2018 09:00'); // Specific date and tim

// const name = "John";

// const message = `Hi ${name}, welcome to our website!`;

// console.log(message); // Output: Hi John, welcome to our website!

// const circle = {
//   radius: 1,

//   draw() {
//     console.log("Draw");
//   },
// };

// // Using Object.assign()

// const another = Object.assign({}, circle);

// // Using Spread Operator

// const anotherClone = { ...circle };

// console.log(Math.random()); // Returns a random number between 0 and 1

// console.log(Math.round(4.7)); // Rounds 4.7 to 5

// const now = new Date();

// console.log(now.toDateString()); // Current date in string format
